services:
  app:
    build: .
    ports:
      - "4567:4567"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"


  networks:

    app-network: 
