services:
  quote-service:
    image: fx/quote-service:dev
    build:
      context: .
      dockerfile: quote-service/Dockerfile
    ports:
      - "8081:8081"

  order-service:
    image: fx/order-service:dev
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8082:8082"

  gateway:
    image: fx/gateway:dev
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - quote-service
      - order-service
